### ISSUE TITLE
consumer.NextMsgs does not work as expected

### ISSUE THREAD

**Issue by tpihl** [nats-io/jsm.go#11]
If remaining number of messages is fewer than, old msgs will be returned instead of receiving a smaller slice.

execution of the provided example code:

connect
check if stream exists
remove old stream
creating stream
creating consumer
start to emit msgs
emitted 15k msgs, all with successful ack  1.387078373s
start consuming, timeout set to 5 seconds but NextMsgs uses context
we're at 14900, time spent is  621.162288ms
0s, received msg strseq: 14991 conseq: 14991 ...acked
0s, received msg strseq: 14992 conseq: 14992 ...acked
0s, received msg strseq: 14993 conseq: 14993 ...acked
0s, received msg strseq: 14994 conseq: 14994 ...acked
NextMsgs, got  7  msgs
4s, received msg strseq: 14995 conseq: 14995 ...acked
4s, received msg strseq: 14996 conseq: 14996 ...acked
4s, received msg strseq: 14997 conseq: 14997 ...acked
4s, received msg strseq: 14998 conseq: 14998 ...acked
4s, received msg strseq: 14999 conseq: 14999 ...acked
4s, received msg strseq: 15000 conseq: 15000 ...acked
4s, received msg strseq: 14995 conseq: 15001 ...acked
NextMsgs, got  7  msgs
8s, received msg strseq: 14996 conseq: 15002 ...acked
8s, received msg strseq: 14997 conseq: 15003 ...acked
8s, received msg strseq: 14998 conseq: 15004 ...acked
8s, received msg strseq: 14999 conseq: 15005 ...acked
8s, received msg strseq: 15000 conseq: 15006 ...acked
8s, received msg strseq: 14996 conseq: 15007 ...acked
8s, received msg strseq: 14997 conseq: 15008 ...acked
NextMsgs, got  7  msgs
14s, received msg strseq: 14998 conseq: 15009 ...acked
14s, received msg strseq: 14999 conseq: 15010 ...acked
14s, received msg strseq: 15000 conseq: 15011 ...acked
14s, received msg strseq: 14998 conseq: 15012 ...acked
14s, received msg strseq: 14999 conseq: 15013 ...acked
14s, received msg strseq: 15000 conseq: 15014 ...acked
14s, received msg strseq: 14998 conseq: 15015 ...acked

```go
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/nats-io/jsm.go"
	"github.com/nats-io/nats.go"
)

func main() {

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// graceful terminate on interrupt
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-c
		cancel()
	}()

	println("connect")
	nc, err := nats.Connect("nats://localhost:4222",
		nats.MaxReconnects(6),
		nats.ReconnectWait(5*time.Second),
		nats.ClosedHandler(func(nc *nats.Conn) {
			println("nats closed")
			cancel()
		}),
		nats.DisconnectHandler(func(nc *nats.Conn) {
			println("nats disconnected")
		}))
	if err != nil {
		panic(err)
	}

	jsm.SetConnection(nc)

	println("check if stream exists")
	exists, err := jsm.IsKnownStream("demostream")
	if err != nil {
		panic(err)
	}

	if exists {
		println("remove old stream")
		// not sure how to remove stream without loading it first
		stream, err := jsm.LoadStream("demostream")
		if err != nil {
			panic(err)
		}
		if err := stream.Delete(); err != nil {
			panic(err)
		}
	}

	println("creating stream")
	stream, err := jsm.NewStream("demostream",
		jsm.FileStorage(),
		jsm.LimitsRetention(),
		jsm.MaxMessages(-1),
		jsm.MaxAge(1<<63-1),
		jsm.Subjects([]string{"test.subject"}...),
		jsm.Replicas(1),                              // TODO: increase when jetstream support it
		jsm.StreamConnection(jsm.WithConnection(nc)), //TODO: handle when we have multiple nc so we connect to correct one
	)
	if err != nil {
		panic(err)
	}

	println("creating consumer")
	consumer, err := stream.NewConsumer(
		jsm.DurableName("democonsumer"),
		jsm.DeliverAllAvailable(),
		jsm.AckWait(2*time.Second),
		jsm.AcknowledgeExplicit(),
		jsm.MaxDeliveryAttempts(10),
		jsm.ConsumerConnection(jsm.WithContext(ctx)),
	)
	if err != nil {
		panic(err)
	}

	println("start to emit msgs")
	startPub := time.Now()
	for n := 0; n < 15000; n++ {
		resp, err := nc.Request("test.subject", []byte(strconv.Itoa(n+1)), 2*time.Second)
		if err != nil {
			panic(err)
		}
		if !bytes.Equal(resp.Data, []byte("+OK")) {
			panic(fmt.Errorf("Did not get ack on emit for no %d", n+1))
		}
	}
	println("emitted 15k msgs, all with successful ack ", time.Since(startPub).String())

	jsm.SetTimeout(5 * time.Second)
	println("start consuming, timeout set to 5 seconds but NextMsgs uses context")
	startCon := time.Now()
	no := 0
	for {
		msgs, err := consumer.NextMsgs(7)
		if errors.Is(err, context.Canceled) {
			return
		}
		if err != nil {
			panic(err)
		}
		if no > 14990 {
			println("NextMsgs, got ", len(msgs), " msgs")
		}
		for _, msg := range msgs {
			no++
			if no == 14990 {
				println("we're at 14900, time spent is ", time.Since(startCon).String())
			}

			i, err := jsm.ParseJSMsgMetadata(msg)
			if err != nil {
				panic(err)
			}

			if no > 14990 {
				print(int(time.Since(startCon).Seconds()), "s, received msg strseq: ", i.StreamSequence(), " conseq: ", i.ConsumerSequence(), " ...")
			}

			if err := msg.Respond(nil); err != nil {
				panic(err)
			}
			if no > 14990 {
				println("acked")
			}
		}
	}
}
```

**Comment by ripienaar** [comment]
As per slack, this function is not for a context that never ends, its use case is a poll that wait for a period, if you pass a ctx that doesn't timeout it will not work. `context.WithCancel(ctx, 10*time.Second)`, I know this doesnt perform as fast as you like, but that is what this function is for.

You're correct in saying it doesn't do what its not designed for basically :)

**Comment by ripienaar** [comment]
As I mentioned on slack, the problem isn't weird out of order deliveries, it's messages that were not acked.

When you pass in a context with no timeout while also having a consumer with a ack timeout of 2 seconds - the NextMsgs() will wait for 7 messages for ever, that's what you are telling it by giving it a waiting-forever-context. Forever is longer than 2 seconds, so yes you ack nowledge the message but AFTER the ack wait time, that acknowledgement is not accepted and the message is redelivered.

If you add a print that shows the `i.Delivered`, you'll see it's redeliveries and that is based on AckWait

```
NextMsgs, got  7  msgs
30s, received msg strseq: 15000 conseq: 15023 deliveries: 2...acked
30s, received msg strseq: 15000 conseq: 15024 deliveries: 3...acked
30s, received msg strseq: 15000 conseq: 15025 deliveries: 4...acked
30s, received msg strseq: 15000 conseq: 15026 deliveries: 5...acked
30s, received msg strseq: 15000 conseq: 15027 deliveries: 6...acked
30s, received msg strseq: 15000 conseq: 15028 deliveries: 7...acked
30s, received msg strseq: 15000 conseq: 15029 deliveries: 8...acked
```

**Comment by tpihl** [comment]
Okay. Understand now, just cannot understand how to use it. Will continue tomorrow i thiink

**Comment by tpihl** [comment]
Answered

**Comment by ripienaar** [comment]
Just to be clear we do agree the way nextmsgs work is awkward and have some meetings planned to code up good examples of the various patterns and to publish that code somewhere. This might well result in some behaviour changes
