### ISSUE TITLE
jsm library sends invalid non configured consumer 

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/jsm.go#12]
MSG_PAYLOAD: ["{\"stream_name\":\"faas-cluster\",\"config\":{\"delivery_subject\":\"\",\"durable_name\":\"faas\",\"start_time\":\"0001-01-01T00:00:00Z\",\"deliver_all\":true,\"deliver_last\":true,\"ack_policy\":\"explicit\",\"ack_wait\":30000000000,\"filter_subject\":\"faas-cluster.faas-request\",\"replay_policy\":\"instant\"}}"]

I would fix this by modifying the consumer format to be similar to ack_policy:
"delivery_policy":"all" or "delivery_policy":"last" 

not have two mutually exclusive fields. 

```
17:59:00  ~/repos/jetstream/nats  master ?1  ./nats -s 0.0.0.0:4222 consumer info faas-cluster  TEST -j
{
  "stream_name": "faas-cluster",
  "name": "TEST",
  "config": {
    "delivery_subject": "",
    "durable_name": "TEST",
    "start_time": "0001-01-01T00:00:00Z",
    "deliver_last": true,
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": -1,
    "filter_subject": "faas-cluster.faas-reques",
    "replay_policy": "instant"
  },
  "state": {
    "delivered": {
      "consumer_seq": 0,
      "stream_seq": 0
    },
    "ack_floor": {
      "consumer_seq": 0,
      "stream_seq": 0
    },
    "pending": null,
    "redelivered": null
  }
}
 17:59:03  ~/repos/jetstream/nats  master ?1  ./nats -s 0.0.0.0:4222 consumer info faas-cluster  TEST2 -j
{
  "stream_name": "faas-cluster",
  "name": "TEST2",
  "config": {
    "delivery_subject": "",
    "durable_name": "TEST2",
    "start_time": "0001-01-01T00:00:00Z",
    "deliver_all": true,
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": -1,
    "filter_subject": "faas-cluster.faas-reques",
    "replay_policy": "instant"
  },
  "state": {
    "delivered": {
      "consumer_seq": 0,
      "stream_seq": 0
    },
    "ack_floor": {
      "consumer_seq": 0,
      "stream_seq": 0
    },
    "pending": null,
    "redelivered": null
  }
}
 17:59:04  ~/repos/jetstream/nats  master ?1 
```

**Comment by ripienaar** [comment]
I'd definitely endorse the change to `delivery_policy` though probably also with a int for consistency, wdyt @derekcollison ?

The various functions to set delivery policies will now reset the 4 options to default before setting the one being asked so this should solve it - however I do not santity check whatever config is passed in the server does that which seems right to me, we dont want to duplicate the full config health check in every one of 30 languages.

**Comment by derekcollison** [comment]
Unfortunately that does not capture all of the delivery policies, we also have by time and by sequence number, they are all mutually exclusive. In Rust this could have been easier with enums also holding state, but in Go not sure how to make this easier. Go defaults to the correct values meaning if you do not put in deliverAll or ByTime etc they are not used.

**Comment by ripienaar** [comment]
I meant more we add a single property that says which one applies and the server take the value of the right other key so the ones not selected can be any value 

Would be clearer what’s active

**Comment by derekcollison** [comment]
Then you have to coordinate two values correctly all the time, the policy and the value (if seq or time based). Are we not just pushing the problem around?

**Comment by ripienaar** [comment]
Possibly but from the point of view as a user interface to the API the current behaviour seems magical and opaque - adding a key to clearly express the intent gives me the chance to be clear about it and a way to look at the JSON and derive what’s being used without really knowing the exact internal behaviours of the API

**Comment by derekcollison** [comment]
ok so add in deliver policy that is enum of

all,
last,
bySeq,
byTime,

and if one of last two additional fields should be non-default values. Correct?

**Comment by ripienaar** [comment]
Yeah something like that I think, maybe make these more snake case for json sake but thats just a nit, that approach. This would even remove one field.

What do you think @matthiashanel ?

**Comment by derekcollison** [comment]
Oh they weren't official naming, just trying to get a sense of it.

**Comment by matthiashanel** [comment]
Looks good to me

**Comment by derekcollison** [comment]
ok any thoughts on timing? Will be breaking change and need to coordinate with this and the jetstream repo.

**Comment by ripienaar** [comment]
Monday first thing ready to merge? Don't think we need to be too prescious about timing tbh, people seem to use the docker releases

**Comment by derekcollison** [comment]
ok sounds good, will get it done this weekend.

**Comment by derekcollison** [comment]
FYI this is a breaking change when restoring from disk from a previous version. I can put some time in to make it work or we could say you need to blow away and saved state?

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats-server/commit/20165494c874ce386ee97143f7f4618260c8f670

**Comment by derekcollison** [comment]
This has been updated but will wait for confirmation before closing.

**Comment by ripienaar** [comment]
blocked on https://github.com/nats-io/nats-server/pull/1340
