### ISSUE TITLE
Best way to read all the messages of a pull stream from the first to the last

### ISSUE THREAD

**Issue by laszbalo** [nats-io/jsm.go#125]
Hi,

could you please somebody advise on the best way to read all the messages from a pull stream with(or if it is not supported, without ) this library?

I have a stream with a single `hello` message.

```shell
$ nats req "FOO.BAR" hello
```

I tried the following code:

```golang
package main

import (
  "fmt"
  "github.com/nats-io/nats.go"
  "github.com/nats-io/jsm.go"
)

func main() {
  nc, _ := nats.Connect(nats.DefaultURL)

  stream, err := jsm.LoadOrNewStreamFromDefault(
    "MYSTREAM",
    jsm.DefaultStreamConfiguration,
    jsm.Subjects("FOO.*"),
    jsm.StreamConnection(jsm.WithConnection(nc)),
    jsm.FileStorage(),
    jsm.DiscardNew(),
  )

  if err != nil {
    panic(err)
  }

  consumer, err := stream.LoadOrNewConsumerFromDefault(
    "FOO",
    jsm.SampledDefaultConsumer,
    jsm.DurableName("MYSTREAM"),
  )

  if err != nil {
    panic(err)
  }


  // Load all the events ...
  for {
    msg, err := consumer.NextMsg()

    if err != nil {
      fmt.Println("Error while reading a message:", err)
      continue
    }
    fmt.Println(".MESSAGE:", msg)
    meta, err := jsm.ParseJSMsgMetadata(msg)
    if err != nil {
      fmt.Println(err)
      continue
    }
    fmt.Println(meta)
  }
}
```

The above code is an infinite loop, which most of the times just times out, but after a random number of time outs it reads the first message from the stream.

How can one accomplish my task of just iterating over all of the messages in the stream and after the last message just stop the iteration?

**Comment by ripienaar** [comment]
Can you try setting UseOldRequest() on the nats connection?

**Comment by laszbalo** [comment]
Did you mean the UseOldRequestStyle() setting? I tried the following code but it did not help:

```golang
  //nc, _ := nats.Connect(nats.DefaultURL)
  nc, _ := nats.Connect(
    nats.DefaultURL, 
    nats.UseOldRequestStyle(),
  )
```

**Comment by ripienaar** [comment]
Ok will check for you tomorrow

**Comment by ripienaar** [comment]
So when you say:

> which most of the times just times out, but after a random number of time outs it reads the first message from the stream.

do you mean it sits and waits and timeouts while there's a message already in the stream? I cant reproduce that, for me it always gets the available messages and only starts timeouts when no messages are there.

The reason you see timeouts then a message and timeouts is because you dont acknowledge the message so its repeatedly redelivered

```
&{MYSTREAM MYSTREAM 2 3 1 {180866563 63733949171 0xbb6240}}
Error while reading a message: context deadline exceeded
.MESSAGE: &{FOO.x $JS.ACK.MYSTREAM.MYSTREAM.3.1.4.1598352316920516285 map[] [49] 0xc0002ee000 <nil> <nil>}
&{MYSTREAM MYSTREAM 1 4 3 {920516285 63733949116 0xbb6240}}
Error while reading a message: context deadline exceeded
Error while reading a message: context deadline exceeded
Error while reading a message: context deadline exceeded
Error while reading a message: context deadline exceeded
.MESSAGE: &{FOO.x $JS.ACK.MYSTREAM.MYSTREAM.2.2.5.1598352371180866563 map[] [49] 0xc0002ee000 <nil> <nil>}
&{MYSTREAM MYSTREAM 2 5 2 {180866563 63733949171 0xbb6240}}
Error while reading a message: context deadline exceeded
.MESSAGE: &{FOO.x $JS.ACK.MYSTREAM.MYSTREAM.4.1.6.1598352316920516285 map[] [49] 0xc0002ee000 <nil> <nil>}
&{MYSTREAM MYSTREAM 1 6 4 {920516285 63733949116 0xbb6240}}
Error while reading a message: context deadline exceeded
Error while reading a message: context deadline exceeded
Error while reading a message: context deadline exceeded
Error while reading a message: context deadline exceeded
.MESSAGE: &{FOO.x $JS.ACK.MYSTREAM.MYSTREAM.3.2.7.1598352371180866563 map[] [49] 0xc0002ee000 <nil> <nil>}
&{MYSTREAM MYSTREAM 2 7 3 {180866563 63733949171 0xbb6240}}
Error while reading a message: context deadline exceeded
.MESSAGE: &{FOO.x $JS.ACK.MYSTREAM.MYSTREAM.5.1.8.1598352316920516285 map[] [49] 0xc0002ee000 <nil> <nil>}
```

> How can one accomplish my task of just iterating over all of the messages in the stream and after the last message just stop the iteration?

We dont support reading a stream up to last and then stopping, we are intending to add some metadata in addition to the metadata already there that would tell you the max stream sequence and so you could use that to know when to stop - even then though, if you filter by subject that wont help.  Conceptually a stream isnt really ending :)

**Comment by laszbalo** [comment]
> do you mean it sits and waits and timeouts while there's a message already in the stream?

No. It always reads the message if there is one in the stream. Sorry, I just tried to explain the redelivery thing. I thought that `NextMsg()` acknowledge the message for me.

Personally I would like to do two things with a consumer:

1. Listen on it forever

```golang
for {
    msg, _, err := consumer.NextMsg()
}
```

2. Read from it until there are no more messages left and stop the iteration (in a way we iterate over a slice)

```golang
for {
  msg, done, err := consumer.NextMsg()
  
  if done {
    break
  }  
}
```

> Conceptually a stream isnt really ending :)

Actually that's quite bad news for me. I was hoping to try JetStream out on a simple project as the main data store.

Thanks again for your help!

**Comment by laszbalo** [comment]
Hi,

I came back after some time to see how this project evolving, and found the `Stream Pager` struct, and it seems to me that it can [do](https://github.com/nats-io/jsm.go/blob/f01998f00c04580dc0241b8b3a17e6971d04ab4e/stream_pager.go#L118) exactly the same thing what I wanted to achieve a couple months ago, namely iterating over all the messages in a stream, and stopping after returned the last.

Could you please someone comment on this?

**Comment by ripienaar** [comment]
Stream pager is nice, but its more a admin thing imo.

If all you want is stop when the end is reached you can parse the message metadata and check how many remains, this works with any consumer

https://github.com/nats-io/jsm.go/blob/f01998f00c04580dc0241b8b3a17e6971d04ab4e/msginfo.go#L67

**Comment by laszbalo** [comment]
Thank you @ripienaar  for your answer. However, each time I am trying to get the pending count, I awlays get `mat.MaxUint64`. This code block never runs: https://github.com/nats-io/jsm.go/blob/f01998f00c04580dc0241b8b3a17e6971d04ab4e/msginfo.go#L94

Seems to me that the server is not sending the pending count or the sent message is not long enough. Is there a way I has to opt in?

I am using the latest docker image, my version of nats server is `2.2.0-beta.15`.

**Comment by ripienaar** [comment]
beta 15 is quite old, try latest - its a newish feature.

**Comment by laszbalo** [comment]
Thanks, working great after building the nats server and client from source.
