### ISSUE TITLE
Missing DeliverNew, DeliverLast, DeliverNext methods

### ISSUE THREAD

**Issue by syacko** [nats-io/jsm.go#130]
DeliverAllAvailable() exists for the creation of a consumer.  There are no functions for DeliverPolicy of new, last or next.  

```
func DeliverAllAvailable() ConsumerOption {
	return func(o *ConsumerCfg) error {
		resetDeliverPolicy(o)
		o.ConsumerConfig.DeliverPolicy = api.DeliverAll
		return nil
	}
}
```
Recommended:
```
func DeliverNextAvailable() ConsumerOption {
	return func(o *ConsumerCfg) error {
		resetDeliverPolicy(o)
		o.ConsumerConfig.DeliverPolicy = api.DeliverNext
		return nil
	}
}
func DeliverNew() ConsumerOption {
	return func(o *ConsumerCfg) error {
		resetDeliverPolicy(o)
		o.ConsumerConfig.DeliverPolicy = api.DeliverNew
		return nil
	}
}
func DeliverLast() ConsumerOption {
	return func(o *ConsumerCfg) error {
		resetDeliverPolicy(o)
		o.ConsumerConfig.DeliverPolicy = api.DeliverLast
		return nil
	}
}
```

**Comment by ripienaar** [comment]
StartWithLastReceived(), StartWithNextReceived()

There is no DeliverNew only DeliverNext

Not the best names I bet but I mimicked streaming server clients for these

**Comment by syacko** [comment]
Thank you for the quick reply.  I will move forward with these functions.

**Comment by syacko** [comment]
I have looked and there is no DeliveryNext existing.  How would `StartWithLastReceived()` or `StartWithNextReceived()` map to "last" or "Next"

**Comment by syacko** [comment]
Ok, this looks like it works.  Thank you for the quick reply.
