### ISSUE TITLE
question: can jsm.ParseJSMMetadata (or another helper) also provide metadata for StoredMsg

### ISSUE THREAD

**Issue by tpihl** [nats-io/jsm.go#14]
for push consumer:

can jsm.ParseJSMMetadata (or another helper) also provide metadata for the StoredMsg?

This would avoid a extra roundtrip to retrive the stored message just to get it's metadata (time and subject, both of them needed if the any of the event's data is in the subject and/or if the actual time the event was emitted/became visible is needed). 

It is otherwise one extra roundtrip and one extra haul of the msg.Data for each received msg from the push consumer if it it's solved clientside.

**Comment by ripienaar** [comment]
At present no, that's not made visible to the consumer. The subject you do know though based on `msg.Subject`

**Comment by tpihl** [comment]
Calling stream.LoadMsg for each msg makes processing aprox 7 times slower (7 seconds instead of sub-second for 50k msgs on localhost server)

**Comment by ripienaar** [comment]
yeah you really should not be doing that - this sounds to me like something you probably should put in your body - but I think we could expose it in the same way as other metadata in theory

what do you think @derekcollison

**Comment by derekcollison** [comment]
The message you get with a consumer has a reply subject that has metadata in it that exposes consumer sequence number and store sequence number. The only thing you do not get with a normal consumer is the timestamp. Do you have a specific need for the timestamp?

**Comment by tpihl** [comment]
Hi. Sorry for slow answer. Yes, actually. 

1st. Replacing stan with jsm I loose the metadata available in stan (i.e. from when is this msg). That metadata is used for msgs that lack time in the message to calculate age of the message or compare  with other messages time stamp to find order between messages (stan does not support compound streams, but even with compound streams, we will end up where we have messages from two different streams and when they overlap, we need to know in what order they where issued). 

2nd. In-stream-enrichment with parallel reading the data stream and the enrichment data stream is only possible to rerun if the original (stream) time stamps are available so I know when to increment my read-view with the next msg from the enrichment stream.

**Comment by ripienaar** [comment]
I think it’s reasonable to put the time in unixnanos at the end of the metadata we expose now. 

Certainly no one should be going to the source stream on every message to get this that’s for sure. 

@derekcollison ?

**Comment by derekcollison** [comment]
This is for normal message consumption via consumers yes?

**Comment by ripienaar** [comment]
Yes, so just a extra bit of metadata along with delivery count, stream name etc

**Comment by derekcollison** [comment]
Any thoughts on format and resolution? just int string with secs or ns from epoch? I don't think we could use a time formatted string.

**Comment by ripienaar** [comment]
Yeah unix nano in UTC

**Comment by ripienaar** [comment]
I took a stab at this https://github.com/nats-io/nats-server/pull/1351

**Comment by derekcollison** [comment]
Will take a look.

**Comment by ripienaar** [comment]
https://github.com/nats-io/jsm.go/pull/28
