### ISSUE TITLE
Multiple subscribers to the same stream don't receive messages

### ISSUE THREAD

**Issue by fdmontero** [nats-io/jsm.go#188]
Hello.

I am experienced some problems with this library v0.20.0. I don't if because there is a bug or because I am not creating consumers properly.

I have created a stream with subjects "TIMESERIES.*".
If I created one consumers and start pulling messages using NextMsgContext I can receive messages successfuly. I have tested with consumer's FilterSubject set to "TIMESERIES.IN", "TIMESERIES.PERFORMANCE" and "TIMESERIES.PREDICTIVE". 

If I create the stream and create 2 consumers, one with FilterSubject set to "TIMESERIES.PERFORMANCE" and another set to "TIMESERIES.PREDICTIVE" I am not able to receive any message in any consumer. Both consumers have different Durable names.

I have tried creating the consumers using stream.LoadOrNewConsumerFromDefault and also with manager.LoadOrNewConsumerFromDefault.

Could someone help me with this issue, please?

**Comment by ripienaar** [comment]
can you show me your stream and consumer configuration please? `nats s info TIMESERIES -j` and ditto for a consumer

**Comment by fdmontero** [comment]
Hi, thak you for your quick response. 

Here are the outputs you asked me.
nats s info TIMESERIES -j
{
  "config": {
    "name": "TIMESERIES",
    "subjects": [
      "TIMESERIES.*"
    ],
    "retention": "limits",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 3600000000000,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1,
    "duplicate_window": 120000000000
  },
  "state": {
    "messages": 6,
    "bytes": 1065,
    "first_seq": 11,
    "first_ts": "2021-02-08T14:27:29.643388679Z",
    "last_seq": 16,
    "last_ts": "2021-02-08T14:27:29.643586773Z",
    "consumer_count": 2
  }
}
#################################################################################
nats c ls
? Select a Stream TIMESERIES
Consumers for Stream TIMESERIES:

        TestMultipleTopic-00
        TestMultipleTopic-01
#################################################################################

nats c info TIMESERIES TestMultipleTopic-00 -j
{
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-00",
  "config": {
    "durable_name": "TestMultipleTopic-00",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PERFORMANCE",
    "replay_policy": "instant",
    "sample_freq": "100%"
  },
  "created": "2021-02-08T14:27:29.630859081Z",
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 13
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 10
  },
  "num_pending": 1,
  "num_redelivered": 0
}

#################################################################################

nats c info TIMESERIES TestMultipleTopic-01 -j
{
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-01",
  "config": {
    "durable_name": "TestMultipleTopic-01",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PREDICTIVE",
    "replay_policy": "instant",
    "sample_freq": "100%"
  },
  "created": "2021-02-08T14:27:29.632736893Z",
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 15
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 10
  },
  "num_pending": 1,
  "num_redelivered": 0
}

Thank you
Regards

**Comment by ripienaar** [comment]
OK, seems like fairly standard stuff, can you also confirm ```nats c next TIMESERIES TestMultipleTopic-01``` (and with the other consumer) have the same problem?

**Comment by fdmontero** [comment]
Hi.

Using NATS I can read messages, so it seems there is a problem with the creation of the consumers in the code. If it could help I have seen a strange behaviour that I cannot reproduce again. The consumers created in code were able to receive one message after consuming from the CLI.

Thak you
Regards

####################################################################################
nats c next TIMESERIES TestMultipleTopic-00
--- subject: TIMESERIES.PERFORMANCE

Headers:

  Id: SomeBoiler#OUT.ISETROPIC.EFF

Data:


{"timestamp":1607011951,"tag":"SomeBoiler#OUT.ISETROPIC.EFF","value":0.34,"quality":0}

Acknowledged message
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-00
--- subject: TIMESERIES.PERFORMANCE

Headers:

  Id: SomeBoiler#OUT.OVERALL.EFF

Data:


{"timestamp":1606830882,"tag":"SomeBoiler#OUT.OVERALL.EFF","value":0.4242,"quality":0}

Acknowledged message
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-01
--- subject: TIMESERIES.PREDICTIVE

Headers:

  Id: SomeTV.MODEL1.SIGNAL1.REAL

Data:


{"timestamp":1606830882,"tag":"SomeTV.MODEL1.SIGNAL1.REAL","value":4242.42,"quality":0}

Acknowledged message
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-01
--- subject: TIMESERIES.PREDICTIVE

Headers:

  Id: SomeTV.MODEL1.SIGNAL1.RESID

Data:


{"timestamp":1607011951,"tag":"SomeTV.MODEL1.SIGNAL1.RESID","value":0.04,"quality":0}

Acknowledged message
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-00
nats: error: could not load next message: context deadline exceeded
####################################################################################

**Comment by ripienaar** [comment]
you can add `--trace` to the cli to see what API calls its making and such to compare with your code

**Comment by fdmontero** [comment]
Here are output with trace.

nats c info TIMESERIES TestMultipleTopic-00 -j --trace
17:21:01 >>> $JS.API.STREAM.NAMES
{"offset":0}

17:21:01 <<< $JS.API.STREAM.NAMES
{
  "type": "io.nats.jetstream.api.v1.stream_names_response",
  "total": 3,
  "offset": 0,
  "limit": 1024,
  "streams": [
    "RESULTS",
    "TASKS",
    "TIMESERIES"
  ]
}

17:21:01 >>> $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-00


17:21:01 <<< $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-00
{
  "type": "io.nats.jetstream.api.v1.consumer_info_response",
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-00",
  "created": "2021-02-08T17:20:57.391958859Z",
  "config": {
    "durable_name": "TestMultipleTopic-00",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PERFORMANCE",
    "replay_policy": "instant",
    "sample_freq": "100%",
    "max_waiting": 512
  },
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 199
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_ack_pending": 1,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 1,
  "cluster": {
    "leader": "NBTVEWFWAM4VKOJN2LMQYNJ4ITOSJZAAKMMMOIBVG7UCTYF577WCGBCT"
  }
}

17:21:01 >>> $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-00


17:21:01 <<< $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-00
{
  "type": "io.nats.jetstream.api.v1.consumer_info_response",
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-00",
  "created": "2021-02-08T17:20:57.391958859Z",
  "config": {
    "durable_name": "TestMultipleTopic-00",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PERFORMANCE",
    "replay_policy": "instant",
    "sample_freq": "100%",
    "max_waiting": 512
  },
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 199
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_ack_pending": 1,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 1,
  "cluster": {
    "leader": "NBTVEWFWAM4VKOJN2LMQYNJ4ITOSJZAAKMMMOIBVG7UCTYF577WCGBCT"
  }
}

17:21:01 >>> $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-00


17:21:01 <<< $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-00
{
  "type": "io.nats.jetstream.api.v1.consumer_info_response",
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-00",
  "created": "2021-02-08T17:20:57.391958859Z",
  "config": {
    "durable_name": "TestMultipleTopic-00",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PERFORMANCE",
    "replay_policy": "instant",
    "sample_freq": "100%",
    "max_waiting": 512
  },
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 199
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_ack_pending": 1,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 1,
  "cluster": {
    "leader": "NBTVEWFWAM4VKOJN2LMQYNJ4ITOSJZAAKMMMOIBVG7UCTYF577WCGBCT"
  }
}

{
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-00",
  "config": {
    "durable_name": "TestMultipleTopic-00",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PERFORMANCE",
    "replay_policy": "instant",
    "sample_freq": "100%"
  },
  "created": "2021-02-08T17:20:57.391958859Z",
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 199
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_pending": 1,
  "num_redelivered": 0
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-00 --trace
--- subject: TIMESERIES.PERFORMANCE

Headers:

  Id: SomeBoiler#OUT.OVERALL.EFF

Data:


{"timestamp":1606830882,"tag":"SomeBoiler#OUT.OVERALL.EFF","value":0.4242,"quality":0}

Acknowledged message
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-00 --trace
--- subject: TIMESERIES.PERFORMANCE

Headers:

  Id: SomeBoiler#OUT.ISETROPIC.EFF

Data:


{"timestamp":1607011951,"tag":"SomeBoiler#OUT.ISETROPIC.EFF","value":0.34,"quality":0}

Acknowledged message
####################################################################################
nats c info TIMESERIES TestMultipleTopic-01 -j --trace
17:22:26 >>> $JS.API.STREAM.NAMES
{"offset":0}

17:22:26 <<< $JS.API.STREAM.NAMES
{
  "type": "io.nats.jetstream.api.v1.stream_names_response",
  "total": 3,
  "offset": 0,
  "limit": 1024,
  "streams": [
    "RESULTS",
    "TASKS",
    "TIMESERIES"
  ]
}

17:22:26 >>> $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-01


17:22:26 <<< $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-01
{
  "type": "io.nats.jetstream.api.v1.consumer_info_response",
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-01",
  "created": "2021-02-08T17:20:57.39351279Z",
  "config": {
    "durable_name": "TestMultipleTopic-01",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PREDICTIVE",
    "replay_policy": "instant",
    "sample_freq": "100%",
    "max_waiting": 512
  },
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 201
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_ack_pending": 1,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 1,
  "cluster": {
    "leader": "NBTVEWFWAM4VKOJN2LMQYNJ4ITOSJZAAKMMMOIBVG7UCTYF577WCGBCT"
  }
}

17:22:26 >>> $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-01


17:22:26 <<< $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-01
{
  "type": "io.nats.jetstream.api.v1.consumer_info_response",
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-01",
  "created": "2021-02-08T17:20:57.39351279Z",
  "config": {
    "durable_name": "TestMultipleTopic-01",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PREDICTIVE",
    "replay_policy": "instant",
    "sample_freq": "100%",
    "max_waiting": 512
  },
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 201
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_ack_pending": 1,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 1,
  "cluster": {
    "leader": "NBTVEWFWAM4VKOJN2LMQYNJ4ITOSJZAAKMMMOIBVG7UCTYF577WCGBCT"
  }
}

17:22:26 >>> $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-01


17:22:26 <<< $JS.API.CONSUMER.INFO.TIMESERIES.TestMultipleTopic-01
{
  "type": "io.nats.jetstream.api.v1.consumer_info_response",
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-01",
  "created": "2021-02-08T17:20:57.39351279Z",
  "config": {
    "durable_name": "TestMultipleTopic-01",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PREDICTIVE",
    "replay_policy": "instant",
    "sample_freq": "100%",
    "max_waiting": 512
  },
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 201
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_ack_pending": 1,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 1,
  "cluster": {
    "leader": "NBTVEWFWAM4VKOJN2LMQYNJ4ITOSJZAAKMMMOIBVG7UCTYF577WCGBCT"
  }
}

{
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-01",
  "config": {
    "durable_name": "TestMultipleTopic-01",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PREDICTIVE",
    "replay_policy": "instant",
    "sample_freq": "100%"
  },
  "created": "2021-02-08T17:20:57.39351279Z",
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 201
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 198
  },
  "num_pending": 1,
  "num_redelivered": 0
}
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-01 --trace
--- subject: TIMESERIES.PREDICTIVE

Headers:

  Id: SomeTV.MODEL1.SIGNAL1.REAL

Data:


{"timestamp":1606830882,"tag":"SomeTV.MODEL1.SIGNAL1.REAL","value":4242.42,"quality":0}

Acknowledged message
####################################################################################
201ec055c28f:~#  nats c next TIMESERIES TestMultipleTopic-01 --trace
--- subject: TIMESERIES.PREDICTIVE

Headers:

  Id: SomeTV.MODEL1.SIGNAL1.RESID

Data:


{"timestamp":1607011951,"tag":"SomeTV.MODEL1.SIGNAL1.RESID","value":0.04,"quality":0}

Acknowledged message

**Comment by ripienaar** [comment]
OK, but what I am getting at is, it works on the CLI with streams and consumers you made in code right? In that case how do you try to fetch the message in your code?

The --trace in `nats c next` will show you how I do it in the CLI so you can perhaps compare what yours does in code and narrow it down?

**Comment by fdmontero** [comment]
Hi.

Please find attached the code I am using to create a subscriber.

Thanks
[subscriber.txt](https://github.com/nats-io/jsm.go/files/5945536/subscriber.txt)

**Comment by fdmontero** [comment]
And the way I am creating publisher and consumer and publishing messages:

`func TestMultipleTopic(t *testing.T) {
	//method := "TestNestedTopic"
	// t.Skip("library jsm does not allow multiple subscribers in the same stream.")

	defer func() {
		if r := recover(); r != nil {
			t.Errorf("test paniced: %v", r)
		}
	}()
	topic1 := messageQueue.TopicTSPerformance
	topic2 := messageQueue.TopicTSPredictive
	opts.Name = "TestMultipleTopic"

	sub, pub, _, err := initTests()
	if err != nil {
		t.Fatalf("error creating all stuff: %s", fmt.Errorf("%w", err))
	}

	doneCh := make(chan bool)
	recCh := make(chan struct{})

	msgCh, err := sub.Subscribe(strings.Join([]string{topic1.String(), topic2.String()}, ","), doneCh)
	if err != nil {
		t.Fatalf("error subscribing: %v", err)
	}

	data := map[messageQueue.Topic][]testdata.Observation{
		topic1: testdata.TestObservations[topic1],
		topic2: testdata.TestObservations[topic2],
	}

	errCh := testdata.ObservationsListenLoop(msgCh, data, true)
	go func() {
		for err := range errCh {
			t.Error(err)
		}
		close(recCh)
	}()

	data[messageQueue.TopicTSIN] = testdata.TestObservations[messageQueue.TopicTSIN]
	if err := publishObservations(pub, data); err != nil {
		t.Error(err)
	}

	select {
	case <-time.After(20 * time.Minute):
		close(doneCh)
		t.Errorf("timeout waiting for messages")
	case <-recCh:
		close(doneCh)
	}

	sub.Terminate()
	pub.Terminate()
}
`
If I only set one topic when subscribing it works fine.

**Comment by ripienaar** [comment]
it should work, but can you try make a mgr instance for each of your consumers

**Comment by fdmontero** [comment]
I have created a manager for each consumer, but still have the same behavior.

Executing several tests, ramdomly I can get some messages:

{"level":"debug","timestamp":"2021-02-08T18:49:00.199241462+01:00","logger":"natslayer.Subscribe","msg":"received message","message":{"Subject":"TIMESERIES.PERFORMANCE","Reply":"$JS.ACK.TIMESERIES.TestMultipleTopic-00.1.241.1.1612806540199037654.0","Header":{"Id":["SomeBoiler#OUT.OVERALL.EFF"]},"Data":"eyJ0aW1lc3RhbXAiOjE2MDY4MzA4ODIsInRhZyI6IlNvbWVCb2lsZXIjT1VULk9WRVJBTEwuRUZGIiwidmFsdWUiOjAuNDI0MiwicXVhbGl0eSI6MH0=","Sub":{"Subject":"_INBOX.tta6l3lpdJtkMGtNaGrvfC.*","Queue":"","ConsumerConfig":null}}}
{"level":"debug","timestamp":"2021-02-08T18:49:00.199353889+01:00","logger":"natslayer.Subscribe","msg":"consumer waiting for messages available","name":"TestMultipleTopic-01","consumers":["TestMultipleTopic-00","TestMultipleTopic-01"]}
{"level":"debug","timestamp":"2021-02-08T18:49:00.199698555+01:00","logger":"natslayer.Subscribe","msg":"acknowledge message"}
{"level":"debug","timestamp":"2021-02-08T18:49:00.199708056+01:00","logger":"natslayer.Subscribe","msg":"received message","message":{"Subject":"TIMESERIES.PREDICTIVE","Reply":"$JS.ACK.TIMESERIES.TestMultipleTopic-01.1.243.1.1612806540199110029.1","Header":{"Id":["SomeTV.MODEL1.SIGNAL1.REAL"]},"Data":"eyJ0aW1lc3RhbXAiOjE2MDY4MzA4ODIsInRhZyI6IlNvbWVUVi5NT0RFTDEuU0lHTkFMMS5SRUFMIiwidmFsdWUiOjQyNDIuNDIsInF1YWxpdHkiOjB9","Sub":{"Subject":"_INBOX.tta6l3lpdJtkMGtNaGrvfC.*","Queue":"","ConsumerConfig":null}}}
{"level":"debug","timestamp":"2021-02-08T18:49:00.19974425+01:00","logger":"natslayer.Subscribe","msg":"consumer waiting for messages available","name":"TestMultipleTopic-00","consumers":["TestMultipleTopic-00","TestMultipleTopic-01"]}
{"level":"debug","timestamp":"2021-02-08T18:49:00.199998898+01:00","logger":"natslayer.Subscribe","msg":"consumer waiting for messages available","name":"TestMultipleTopic-01","consumers":["TestMultipleTopic-00","TestMultipleTopic-01"]}
[nastslayer_test.txt](https://github.com/nats-io/jsm.go/files/5945702/nastslayer_test.txt)
[subscriber.txt](https://github.com/nats-io/jsm.go/files/5945703/subscriber.txt)

**Comment by ripienaar** [comment]
Will need to see at the point of you experiencing the problem what does the nats c info show for the consumer - I need to see the state - ack floor etc

These code files you're pasting is quite hard for me to pare they're very verbose and detailed and I cant really run them locally, so quite difficult for me to reproduce with those

**Comment by fdmontero** [comment]
This status is taken when both consumers are waiting in sentence: `msg, err := consumer.NextMsgContext(ctx)`

201ec055c28f:~# nats c info TIMESERIES TestMultipleTopic-00 -j
{
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-00",
  "config": {
    "durable_name": "TestMultipleTopic-00",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PERFORMANCE",
    "replay_policy": "instant",
    "sample_freq": "100%"
  },
  "created": "2021-02-08T18:00:30.639398377Z",
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 255
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 252
  },
  "num_pending": 1,
  "num_redelivered": 0
}
####################################################################################
201ec055c28f:~# nats c info TIMESERIES TestMultipleTopic-01 -j
{
  "stream_name": "TIMESERIES",
  "name": "TestMultipleTopic-01",
  "config": {
    "durable_name": "TestMultipleTopic-01",
    "deliver_policy": "all",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "max_deliver": 3,
    "filter_subject": "TIMESERIES.PREDICTIVE",
    "replay_policy": "instant",
    "sample_freq": "100%"
  },
  "created": "2021-02-08T18:00:30.640930385Z",
  "delivered": {
    "consumer_seq": 1,
    "stream_seq": 257
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 252
  },
  "num_pending": 1,
  "num_redelivered": 0
}
201ec055c28f:~#

**Comment by ripienaar** [comment]
Ok I will try to make easier to reproduce code tomorrow and see 

I would stop using NextMsgContext() though it is ONLY for cases where you have W context with a timeout not this never ending contexts.

**Comment by ripienaar** [comment]
Please also set nats.UseOldRequestStyle() on your nats connection

**Comment by fdmontero** [comment]
Thank you so much for your valuable help, now I am receiving all messages.

Best regards

**Comment by ripienaar** [comment]
Great. In master of this package it will error in cases where UseOld was needed and not given. Sorry for the hassle :)
