### ISSUE TITLE
LoadOrNewConsumer is not working well

### ISSUE THREAD

**Issue by zhenqianz** [nats-io/jsm.go#255]
So I have this code
```
orderConsumer, err = mgr.LoadOrNewConsumer("ORDERS",
	"CONSUMER_NAME",
	jsm.DurableName("CONSUMER_DURABLE"),
	jsm.AcknowledgeExplicit(),
	jsm.ReplayInstantly(),
	jsm.SamplePercent(20),
	jsm.StartAtTimeDelta(3*time.Hour))
if err != nil {
	log.Fatalf("Failed to create a jetstream consumer! Reason: %q\n", err)
}
```

When the consumer stops and restart, it got a `consumer already exists` error. 
This also happens when you have multiple consumers with the same name and durable (supposedly they can connect just well, similar with nats-streaming's queue subscribe. CMIIW).

I checked the code, then I found out that when the consumer is not found, then a new consumer is created by the `durable_name` instead of the `name`. And when loading consumer, it searches by the `name`, not the `durable_name`.

So far, I can do something like this to handle the error. And it works.
```
	orderConsumer, err := mgr.LoadConsumer("ORDERS",
		"CONSUMER_DURABLE")
	if err != nil {
		log.Printf("Failed to create a jetstream consumer! Reason: %q\n", err)
	}

	if orderConsumer == nil {
		orderConsumer, err = mgr.NewConsumer(event."ORDERS",
			jsm.DurableName("CONSUMER_DURABLE"),
			jsm.AcknowledgeExplicit(),
			jsm.ReplayInstantly(),
			jsm.SamplePercent(20),
			jsm.StartAtTimeDelta(3*time.Hour))
		if err != nil {
			log.Fatalf("Failed to create a jetstream consumer! Reason: %q\n", err)
		}
	}
```
or
```
orderConsumer, err = mgr.LoadOrNewConsumer("ORDERS",
	"CONSUMER_DURABLE",
	jsm.DurableName("CONSUMER_DURABLE"),
	jsm.AcknowledgeExplicit(),
	jsm.ReplayInstantly(),
	jsm.SamplePercent(20),
	jsm.StartAtTimeDelta(3*time.Hour))
if err != nil {
	log.Fatalf("Failed to create a jetstream consumer! Reason: %q\n", err)
}
```

Is there anything I'm missing? Or should the consumer name and durable name be the same?

Thanks in advance.

**Comment by ripienaar** [comment]
I will look but yes durabale and name is the same. When it’s an ephemeral durable is empty but name is set to a generated name. 

For general end user apps you should look at nats.go it now has jetstream helpers. Welcome to use this one of course but it’s tailored a lot to what the CLI needs.

**Comment by zhenqianz** [comment]
Cool. I'll look into the nats.go.

Thanks man

**Comment by ripienaar** [comment]
OK yeah I think this is mainly down to the stutter in durable name.

It's confusing that you have to set durable name in the load argument and in the create settings, probably fixable, but as this is there to support CLI interactions I think its probably bearable for the moment.  

Only improvement I can imagine is to take durable name from the arguments if not given - but hten I have to trigger ephemeral in some other way.  Removing one option but require another.

**Comment by zhenqianz** [comment]
Ok

Btw I have looked into nats.go, and it worked well. 

Thanks
