### ISSUE TITLE
What should I use as a jetstream go client

### ISSUE THREAD

**Issue by aperrot42** [nats-io/jsm.go#258]
Hi,

This is more of a documentation request. As a go developper interacting with Jetstream nats server, should I use :

 - https://github.com/nats-io/nats.go (it contains jsm.go)
 - https://github.com/nats-io/jsm.go (it seems to contain some (a lot of) helpers)

The whole model and logic seems to differ, between pull-push consumers / subcriptions : for instance, using this library, it feels like pull based consumer are kind of "deprecated".

Bref, If you can help me find the current reference implementation of jetstream go client that would be great.

Best,

**Comment by ripienaar** [comment]
This repo is mainly there to support the CLI, end users should use nats.go.

**Comment by aperrot42** [comment]
@ripienaar thanks a lot ! Added that as a SO question if you want to answer it : https://stackoverflow.com/questions/68098471/which-go-client-use-with-nats-jetstream

**Comment by ripienaar** [comment]
I don't use SO personally, so I'll pass on that.
