### ISSUE TITLE
stream configuration message related variables

### ISSUE THREAD

**Issue by scottf** [nats-io/jsm.go#308]
In nats-server, stream.go there is this:

```
type StreamConfig struct {
        ...
	MaxMsgs      int64           `json:"max_msgs"`
	MaxBytes     int64           `json:"max_bytes"`
        ...
	MaxMsgsPer   int64           `json:"max_msgs_per_subject"`
```

In jsm.go, definition for `stream_configuration` the same are defined as

```
"$ref": "#/definitions/golang_uint64"
```

Which one needs to change?

**Comment by scottf** [comment]
agreed, should be uint64. Can zero (0) mean unlimited? Or we could just use the actual max value of uint64. This is a good thing to capture for all the uint64 vars.

**Comment by derekcollison** [comment]
Any setting is signed so -1 means unlimited. All others unsigned.

**Comment by ripienaar** [comment]
Seems like a bug if the limit can only set the limit to about 1/2 of the possible messages (i know, i know, these numbers are so big it doesnt matter in the end of the day) its just weird.

**Comment by derekcollison** [comment]
Common pattern, or used to be. And yes, we seem to be worrying about stuff that is not that important these days.

**Comment by ripienaar** [comment]
Schemas update in https://github.com/nats-io/jsm.go/pull/309
