### ISSUE TITLE
Why consumer's stream_paper is created auto?

### ISSUE THREAD

**Issue by edarha** [nats-io/jsm.go#335]
In my case, When I check consumers in a Streams, I see many consumers' stream_paper is created with pull mode. This makes many messages that cannot ack in these consumers' stream_paper. Can you have me prevent consumer stream_paper auto?

**Comment by ripienaar** [comment]
it's when you run `nats stream view` and do not terminate it nicely

**Comment by edarha** [comment]
can you help me to know how I can terminate `nats stream view` nicely?

**Comment by edarha** [comment]
regarding `consumer stream_paper` just delete is fine or do I have to do anything else?

**Comment by edarha** [comment]
Nice, Thanks a lot

**Comment by edarha** [comment]
Can I ask you about `nats stream view`? How can I just only get messages is acked or un-acked @ripienaar

**Comment by edarha** [comment]
When I run the command `nats stream report` sometimes I see the message's column have a number, sometimes is 0, so I think this number is total messages is un-acked

**Comment by ripienaar** [comment]
Depends on the stream type. If it’s a work queue then yes. Otherwise no.

**Comment by edarha** [comment]
![Screenshot from 2021-10-21 08-26-33](https://user-images.githubusercontent.com/36435846/138195432-c0c700f6-397b-4a75-ab20-ef54cfde79ee.png)


![Screenshot from 2021-10-21 08-22-28](https://user-images.githubusercontent.com/36435846/138195224-e85b2cdb-56a0-4e5e-b074-beaf71702ddd.png)

**Comment by ripienaar** [comment]
Are those not new messages?

**Comment by edarha** [comment]
no, I don't publish new messages

**Comment by ripienaar** [comment]
Anyway, so it’s a bug it seems. Please open a issue under nats-server 

clearly show your configuration, info, times that you run commands etc

**Comment by ripienaar** [comment]
Please open an issue under the nats-server repository.
