### ISSUE TITLE
[Feature Request] Can we add the monitor-related config in context?

### ISSUE THREAD

**Issue by yeqown** [nats-io/jsm.go#511]
Background: https://github.com/nats-io/nats-top/pull/98#issuecomment-1870678870

I'm adding context support in nats-top, [natscontext](https://github.com/nats-io/jsm.go/tree/main/natscontext) is helpful to interact with multi nats clusters, but it doesn't carry the monitor-related config, such as the port (default 8222)

**Comment by yeqown** [comment]
If necessary, I'd love to make a PR

**Comment by ripienaar** [comment]
As per comments in nats top pr no I wouldn’t add it here

nats top needs to  start using the nats network for access to monitor data. It’s the reason it isn’t available as “nats too” - it would be highly desirable to add it to the nats command. 

So I am not  adding things here to prolong its independence.

cc @jnmoyne

**Comment by yeqown** [comment]
I see. So is there any plan to support `nats top` or `nats server top` command yet?

**Comment by ripienaar** [comment]
Need to test a few more things but should be in next release https://github.com/nats-io/natscli/pull/942
