### ISSUE TITLE
Support variable expansion in context file field values

### ISSUE THREAD

**Issue by robinbowes** [nats-io/jsm.go#577]
I'd like to be able to use either `~` or `$HOME` in the value of some fields in nats contexts to specify file locations relative to the current user's home dir, eg:

```
{
  "description": "Example prod",
  "url": "tls://global.example.com:4222",
  "nkey": "~/.keys/nats/example/prod.nkey"
}
```

**Comment by ripienaar** [comment]
@ploubser see if you can get this one going? Lets just do `~` expansing in all the things that can take paths there
